---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - intent.security.protego.com
  resources:
  - securityintentbindings
  - securityintents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.security.protego.com
  resources:
  - securityintentbindings/finalizers
  - securityintents/finalizers
  verbs:
  - update
- apiGroups:
  - intent.security.protego.com
  resources:
  - securityintentbindings/status
  - securityintents/status
  verbs:
  - get
  - patch
  - update
