# permissions for end users to edit securityintentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: protego
    app.kubernetes.io/managed-by: kustomize
  name: securityintentbinding-editor-role
rules:
- apiGroups:
  - intent.security.protego.com
  resources:
  - securityintentbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.security.protego.com
  resources:
  - securityintentbindings/status
  verbs:
  - get
